package com.microsoft.luis.client;
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISAction {
    @com.fasterxml.jackson.annotation.JsonProperty("triggered")
    private java.lang.Boolean _triggered;

    public void setTriggered(java.lang.Boolean triggered) {
        this._triggered = triggered;
    }

    public java.lang.Boolean getTriggered() {
        return _triggered;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("parameters")
    private LUISParameter[] _parameters;

    public void setParameters(LUISParameter[] parameters) {
        this._parameters = parameters;
    }

    public LUISParameter[] getParameters() {
        return _parameters;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("name")
    private java.lang.String _name;

    public void setName(java.lang.String name) {
        this._name = name;
    }

    public java.lang.String getName() {
        return _name;
    }

}