package com.microsoft.luis.client;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

import java.util.Comparator;

public class LUISResult {
    @com.fasterxml.jackson.annotation.JsonProperty("entities")
    private LUISEntity[] _entities;

    public void setEntities(LUISEntity[] entities) {
        this._entities = entities;
    }

    public LUISEntity[] getEntities() {
        return _entities;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("query")
    private java.lang.String _query;

    public void setQuery(java.lang.String query) {
        this._query = query;
    }

    public java.lang.String getQuery() {
        return _query;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("intents")
    private LUISIntent[] _intents;

    /*
    Sort the intents in descending order
     */
    public void sortByIntent() {
        java.util.Arrays.sort(this._intents, new Comparator<LUISIntent>() {
            @Override
            public int compare(LUISIntent a, LUISIntent b) {
                return -1 *  a.getScore().compareTo(b.getScore());
            }
        });
    }

    public void setIntents(LUISIntent[] intents) {
        this._intents = intents;
    }

    public LUISIntent[] getIntents() {
        return _intents;
    }

}
