package com.microsoft.luis.client;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISEntity {
    @com.fasterxml.jackson.annotation.JsonProperty("endIndex")
    private java.lang.Integer _endindex;

    public void setEndindex(java.lang.Integer endindex) {
        this._endindex = endindex;
    }

    public java.lang.Integer getEndindex() {
        return _endindex;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("type")
    private java.lang.String _type;

     public void setType(java.lang.String type) {
        this._type = type;
    }

    public java.lang.String getType() {
        return _type;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("startIndex")
    private java.lang.Integer _startindex;

     public void setStartindex(java.lang.Integer startindex) {
        this._startindex = startindex;
    }

    public java.lang.Integer getStartindex() {
        return _startindex;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("score")
    private java.lang.Double _score;

     public void setScore(java.lang.Double score) {
        this._score = score;
    }

    public java.lang.Double getScore() {
        return _score;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("entity")
    private java.lang.String _entity;

     public void setEntity(java.lang.String entity) {
        this._entity = entity;
    }

    public java.lang.String getEntity() {
        return _entity;
    }

}