package com.microsoft.luis.client;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISIntent {
    @com.fasterxml.jackson.annotation.JsonProperty("actions")
    private LUISAction[] _actions;

    public void setActions(LUISAction[] actions) {
        this._actions = actions;
    }

    public LUISAction[] getActions() {
        return _actions;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("intent")
    private java.lang.String _intent;

     public void setIntent(java.lang.String intent) {
        this._intent = intent;
    }

    public java.lang.String getIntent() {
        return _intent;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("score")
    private java.lang.Double _score;

     public void setScore(java.lang.Double score) {
        this._score = score;
    }

    public java.lang.Double getScore() {
        return _score;
    }

}