package com.microsoft.luis.client;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISParameter {
    @com.fasterxml.jackson.annotation.JsonProperty("value")
    private LUISValue[] _value;

    public void setValue(LUISValue[] value) {
        this._value = value;
    }

    public LUISValue[] getValue() {
        return _value;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("required")
    private java.lang.Boolean _required;

    public void setRequired(java.lang.Boolean required) {
        this._required = required;
    }

    public java.lang.Boolean getRequired() {
        return _required;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("name")
    private java.lang.String _name;

     public void setName(java.lang.String name) {
        this._name = name;
    }

    public java.lang.String getName() {
        return _name;
    }

}